<?php
/**
 * GrantAccessInputTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  AffinidiTdk\Clients\IamClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Iam
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AffinidiTdk\Clients\IamClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GrantAccessInputTest Class Doc Comment
 *
 * @category    Class
 * @description GrantAccessInput
 * @package     AffinidiTdk\Clients\IamClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GrantAccessInputTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GrantAccessInput"
     */
    public function testGrantAccessInput()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "subject_did"
     */
    public function testPropertySubjectDid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rights"
     */
    public function testPropertyRights()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
