<?php
/**
 * UpdateAccessInputTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AffinidiTdk\Clients\IamClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Iam
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AffinidiTdk\Clients\IamClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * UpdateAccessInputTest Class Doc Comment
 *
 * @category    Class
 * @description UpdateAccessInput
 * @package     AffinidiTdk\Clients\IamClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UpdateAccessInputTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UpdateAccessInput"
     */
    public function testUpdateAccessInput()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rights"
     */
    public function testPropertyRights()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
