<?php
/**
 * CorsListNodeChildrenOKTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  AffinidiTdk\Clients\VaultDataManagerClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VaultFileSystem
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AffinidiTdk\Clients\VaultDataManagerClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CorsListNodeChildrenOKTest Class Doc Comment
 *
 * @category    Class
 * @description CorsListNodeChildrenOK
 * @package     AffinidiTdk\Clients\VaultDataManagerClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CorsListNodeChildrenOKTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CorsListNodeChildrenOK"
     */
    public function testCorsListNodeChildrenOK()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cors_list_node_children_ok"
     */
    public function testPropertyCorsListNodeChildrenOk()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
