<?php
/**
 * NodeStatusTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  AffinidiTdk\Clients\VaultDataManagerClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VaultFileSystem
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AffinidiTdk\Clients\VaultDataManagerClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * NodeStatusTest Class Doc Comment
 *
 * @category    Class
 * @description status of current node. INITIALIZED status is used for PROFILE/FILE node that was just created, before file was uploaded in s3 CREATED status is used, when the file for node is uploaded in s3. HIDDEN and DELETED statuses are used for deletion of Nodes
 * @package     AffinidiTdk\Clients\VaultDataManagerClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class NodeStatusTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "NodeStatus"
     */
    public function testNodeStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
