<?php
/**
 * OAuth2TokenAuthorizationDetailsInnerTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AffinidiTdk\Clients\LoginConfigurationClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OidcVpAdapterBackend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AffinidiTdk\Clients\LoginConfigurationClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * OAuth2TokenAuthorizationDetailsInnerTest Class Doc Comment
 *
 * @category    Class
 * @description OAuth2TokenAuthorizationDetailsInner
 * @package     AffinidiTdk\Clients\LoginConfigurationClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class OAuth2TokenAuthorizationDetailsInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OAuth2TokenAuthorizationDetailsInner"
     */
    public function testOAuth2TokenAuthorizationDetailsInner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "credential_configuration_id"
     */
    public function testPropertyCredentialConfigurationId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "credential_identifiers"
     */
    public function testPropertyCredentialIdentifiers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
