<?php
/**
 * WalletDidType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AffinidiTdk\Clients\WalletsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CloudWalletEssentials
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AffinidiTdk\Clients\WalletsClient\Model;
use \AffinidiTdk\Clients\WalletsClient\ObjectSerializer;

/**
 * WalletDidType Class Doc Comment
 *
 * @category Class
 * @description DID method type for the wallet
 * @package  AffinidiTdk\Clients\WalletsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WalletDidType
{
    /**
     * Possible values of this enum
     */
    public const WEB = 'WEB';

    public const KEY = 'KEY';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::WEB,
            self::KEY
        ];
    }
}


