<?php
/**
 * WalletV2DtoKeysInner
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AffinidiTdk\Clients\WalletsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CloudWalletEssentials
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AffinidiTdk\Clients\WalletsClient\Model;

use \ArrayAccess;
use \AffinidiTdk\Clients\WalletsClient\ObjectSerializer;

/**
 * WalletV2DtoKeysInner Class Doc Comment
 *
 * @category Class
 * @package  AffinidiTdk\Clients\WalletsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class WalletV2DtoKeysInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'WalletV2Dto_keys_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'key_id' => 'string',
        'kms_key_id' => 'string',
        'kms_key_ari' => 'string',
        'kms_key_type' => 'string',
        'relationships' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'key_id' => null,
        'kms_key_id' => null,
        'kms_key_ari' => null,
        'kms_key_type' => null,
        'relationships' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'key_id' => false,
        'kms_key_id' => false,
        'kms_key_ari' => false,
        'kms_key_type' => false,
        'relationships' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'key_id' => 'keyId',
        'kms_key_id' => 'kmsKeyId',
        'kms_key_ari' => 'kmsKeyAri',
        'kms_key_type' => 'kmsKeyType',
        'relationships' => 'relationships'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'key_id' => 'setKeyId',
        'kms_key_id' => 'setKmsKeyId',
        'kms_key_ari' => 'setKmsKeyAri',
        'kms_key_type' => 'setKmsKeyType',
        'relationships' => 'setRelationships'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'key_id' => 'getKeyId',
        'kms_key_id' => 'getKmsKeyId',
        'kms_key_ari' => 'getKmsKeyAri',
        'kms_key_type' => 'getKmsKeyType',
        'relationships' => 'getRelationships'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('key_id', $data ?? [], null);
        $this->setIfExists('kms_key_id', $data ?? [], null);
        $this->setIfExists('kms_key_ari', $data ?? [], null);
        $this->setIfExists('kms_key_type', $data ?? [], null);
        $this->setIfExists('relationships', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['key_id'] === null) {
            $invalidProperties[] = "'key_id' can't be null";
        }
        if ($this->container['kms_key_id'] === null) {
            $invalidProperties[] = "'kms_key_id' can't be null";
        }
        if ($this->container['kms_key_ari'] === null) {
            $invalidProperties[] = "'kms_key_ari' can't be null";
        }
        if ($this->container['kms_key_type'] === null) {
            $invalidProperties[] = "'kms_key_type' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets key_id
     *
     * @return string
     */
    public function getKeyId()
    {
        return $this->container['key_id'];
    }

    /**
     * Sets key_id
     *
     * @param string $key_id wallet-scoped key identifier (e.g., \"key-1\")
     *
     * @return self
     */
    public function setKeyId($key_id)
    {
        if (is_null($key_id)) {
            throw new \InvalidArgumentException('non-nullable key_id cannot be null');
        }
        $this->container['key_id'] = $key_id;

        return $this;
    }

    /**
     * Gets kms_key_id
     *
     * @return string
     */
    public function getKmsKeyId()
    {
        return $this->container['kms_key_id'];
    }

    /**
     * Sets kms_key_id
     *
     * @param string $kms_key_id id of the key in KMS
     *
     * @return self
     */
    public function setKmsKeyId($kms_key_id)
    {
        if (is_null($kms_key_id)) {
            throw new \InvalidArgumentException('non-nullable kms_key_id cannot be null');
        }
        $this->container['kms_key_id'] = $kms_key_id;

        return $this;
    }

    /**
     * Gets kms_key_ari
     *
     * @return string
     */
    public function getKmsKeyAri()
    {
        return $this->container['kms_key_ari'];
    }

    /**
     * Sets kms_key_ari
     *
     * @param string $kms_key_ari ari of the key in KMS
     *
     * @return self
     */
    public function setKmsKeyAri($kms_key_ari)
    {
        if (is_null($kms_key_ari)) {
            throw new \InvalidArgumentException('non-nullable kms_key_ari cannot be null');
        }
        $this->container['kms_key_ari'] = $kms_key_ari;

        return $this;
    }

    /**
     * Gets kms_key_type
     *
     * @return string
     */
    public function getKmsKeyType()
    {
        return $this->container['kms_key_type'];
    }

    /**
     * Sets kms_key_type
     *
     * @param string $kms_key_type type of the key in KMS
     *
     * @return self
     */
    public function setKmsKeyType($kms_key_type)
    {
        if (is_null($kms_key_type)) {
            throw new \InvalidArgumentException('non-nullable kms_key_type cannot be null');
        }
        $this->container['kms_key_type'] = $kms_key_type;

        return $this;
    }

    /**
     * Gets relationships
     *
     * @return string|null
     */
    public function getRelationships()
    {
        return $this->container['relationships'];
    }

    /**
     * Sets relationships
     *
     * @param string|null $relationships comma separated relationships
     *
     * @return self
     */
    public function setRelationships($relationships)
    {
        if (is_null($relationships)) {
            throw new \InvalidArgumentException('non-nullable relationships cannot be null');
        }
        $this->container['relationships'] = $relationships;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


