<?php
/**
 * CreateAccountWithProfileInput
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AffinidiTdk\Clients\VaultDataManagerClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VaultFileSystem
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AffinidiTdk\Clients\VaultDataManagerClient\Model;

use \ArrayAccess;
use \AffinidiTdk\Clients\VaultDataManagerClient\ObjectSerializer;

/**
 * CreateAccountWithProfileInput Class Doc Comment
 *
 * @category Class
 * @package  AffinidiTdk\Clients\VaultDataManagerClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateAccountWithProfileInput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreateAccountWithProfileInput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'account_index' => 'float',
        'account_did' => 'string',
        'did_proof' => 'string',
        'alias' => 'string',
        'account_metadata' => 'object',
        'account_description' => 'string',
        'profile_name' => 'string',
        'profile_description' => 'string',
        'profile_metadata' => 'object',
        'edek_info' => '\AffinidiTdk\Clients\VaultDataManagerClient\Model\EdekInfo',
        'dek' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'account_index' => null,
        'account_did' => null,
        'did_proof' => null,
        'alias' => null,
        'account_metadata' => null,
        'account_description' => null,
        'profile_name' => null,
        'profile_description' => null,
        'profile_metadata' => null,
        'edek_info' => null,
        'dek' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'account_index' => false,
        'account_did' => false,
        'did_proof' => false,
        'alias' => false,
        'account_metadata' => false,
        'account_description' => false,
        'profile_name' => false,
        'profile_description' => false,
        'profile_metadata' => false,
        'edek_info' => false,
        'dek' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'account_index' => 'accountIndex',
        'account_did' => 'accountDid',
        'did_proof' => 'didProof',
        'alias' => 'alias',
        'account_metadata' => 'accountMetadata',
        'account_description' => 'accountDescription',
        'profile_name' => 'profileName',
        'profile_description' => 'profileDescription',
        'profile_metadata' => 'profileMetadata',
        'edek_info' => 'edekInfo',
        'dek' => 'dek'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'account_index' => 'setAccountIndex',
        'account_did' => 'setAccountDid',
        'did_proof' => 'setDidProof',
        'alias' => 'setAlias',
        'account_metadata' => 'setAccountMetadata',
        'account_description' => 'setAccountDescription',
        'profile_name' => 'setProfileName',
        'profile_description' => 'setProfileDescription',
        'profile_metadata' => 'setProfileMetadata',
        'edek_info' => 'setEdekInfo',
        'dek' => 'setDek'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'account_index' => 'getAccountIndex',
        'account_did' => 'getAccountDid',
        'did_proof' => 'getDidProof',
        'alias' => 'getAlias',
        'account_metadata' => 'getAccountMetadata',
        'account_description' => 'getAccountDescription',
        'profile_name' => 'getProfileName',
        'profile_description' => 'getProfileDescription',
        'profile_metadata' => 'getProfileMetadata',
        'edek_info' => 'getEdekInfo',
        'dek' => 'getDek'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('account_index', $data ?? [], null);
        $this->setIfExists('account_did', $data ?? [], null);
        $this->setIfExists('did_proof', $data ?? [], null);
        $this->setIfExists('alias', $data ?? [], null);
        $this->setIfExists('account_metadata', $data ?? [], null);
        $this->setIfExists('account_description', $data ?? [], null);
        $this->setIfExists('profile_name', $data ?? [], null);
        $this->setIfExists('profile_description', $data ?? [], null);
        $this->setIfExists('profile_metadata', $data ?? [], null);
        $this->setIfExists('edek_info', $data ?? [], null);
        $this->setIfExists('dek', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['account_index'] === null) {
            $invalidProperties[] = "'account_index' can't be null";
        }
        if ($this->container['account_did'] === null) {
            $invalidProperties[] = "'account_did' can't be null";
        }
        if (!preg_match("/^did:.*$/", $this->container['account_did'])) {
            $invalidProperties[] = "invalid value for 'account_did', must be conform to the pattern /^did:.*$/.";
        }

        if ($this->container['did_proof'] === null) {
            $invalidProperties[] = "'did_proof' can't be null";
        }
        if ($this->container['profile_name'] === null) {
            $invalidProperties[] = "'profile_name' can't be null";
        }
        if ((mb_strlen($this->container['profile_name']) > 255)) {
            $invalidProperties[] = "invalid value for 'profile_name', the character length must be smaller than or equal to 255.";
        }

        if ((mb_strlen($this->container['profile_name']) < 1)) {
            $invalidProperties[] = "invalid value for 'profile_name', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['profile_description']) && (mb_strlen($this->container['profile_description']) > 1000)) {
            $invalidProperties[] = "invalid value for 'profile_description', the character length must be smaller than or equal to 1000.";
        }

        if ($this->container['edek_info'] === null) {
            $invalidProperties[] = "'edek_info' can't be null";
        }
        if ($this->container['dek'] === null) {
            $invalidProperties[] = "'dek' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets account_index
     *
     * @return float
     */
    public function getAccountIndex()
    {
        return $this->container['account_index'];
    }

    /**
     * Sets account_index
     *
     * @param float $account_index number that is used for profile DID derivation
     *
     * @return self
     */
    public function setAccountIndex($account_index)
    {
        if (is_null($account_index)) {
            throw new \InvalidArgumentException('non-nullable account_index cannot be null');
        }
        $this->container['account_index'] = $account_index;

        return $this;
    }

    /**
     * Gets account_did
     *
     * @return string
     */
    public function getAccountDid()
    {
        return $this->container['account_did'];
    }

    /**
     * Sets account_did
     *
     * @param string $account_did DID that is associated with the account number
     *
     * @return self
     */
    public function setAccountDid($account_did)
    {
        if (is_null($account_did)) {
            throw new \InvalidArgumentException('non-nullable account_did cannot be null');
        }

        if ((!preg_match("/^did:.*$/", ObjectSerializer::toString($account_did)))) {
            throw new \InvalidArgumentException("invalid value for \$account_did when calling CreateAccountWithProfileInput., must conform to the pattern /^did:.*$/.");
        }

        $this->container['account_did'] = $account_did;

        return $this;
    }

    /**
     * Gets did_proof
     *
     * @return string
     */
    public function getDidProof()
    {
        return $this->container['did_proof'];
    }

    /**
     * Sets did_proof
     *
     * @param string $did_proof JWT that proves ownership of profile DID by requester
     *
     * @return self
     */
    public function setDidProof($did_proof)
    {
        if (is_null($did_proof)) {
            throw new \InvalidArgumentException('non-nullable did_proof cannot be null');
        }
        $this->container['did_proof'] = $did_proof;

        return $this;
    }

    /**
     * Gets alias
     *
     * @return string|null
     */
    public function getAlias()
    {
        return $this->container['alias'];
    }

    /**
     * Sets alias
     *
     * @param string|null $alias Alias of account
     *
     * @return self
     */
    public function setAlias($alias)
    {
        if (is_null($alias)) {
            throw new \InvalidArgumentException('non-nullable alias cannot be null');
        }
        $this->container['alias'] = $alias;

        return $this;
    }

    /**
     * Gets account_metadata
     *
     * @return object|null
     */
    public function getAccountMetadata()
    {
        return $this->container['account_metadata'];
    }

    /**
     * Sets account_metadata
     *
     * @param object|null $account_metadata Metadata of account
     *
     * @return self
     */
    public function setAccountMetadata($account_metadata)
    {
        if (is_null($account_metadata)) {
            throw new \InvalidArgumentException('non-nullable account_metadata cannot be null');
        }
        $this->container['account_metadata'] = $account_metadata;

        return $this;
    }

    /**
     * Gets account_description
     *
     * @return string|null
     */
    public function getAccountDescription()
    {
        return $this->container['account_description'];
    }

    /**
     * Sets account_description
     *
     * @param string|null $account_description Description of account
     *
     * @return self
     */
    public function setAccountDescription($account_description)
    {
        if (is_null($account_description)) {
            throw new \InvalidArgumentException('non-nullable account_description cannot be null');
        }
        $this->container['account_description'] = $account_description;

        return $this;
    }

    /**
     * Gets profile_name
     *
     * @return string
     */
    public function getProfileName()
    {
        return $this->container['profile_name'];
    }

    /**
     * Sets profile_name
     *
     * @param string $profile_name Name of the profile node
     *
     * @return self
     */
    public function setProfileName($profile_name)
    {
        if (is_null($profile_name)) {
            throw new \InvalidArgumentException('non-nullable profile_name cannot be null');
        }
        if ((mb_strlen($profile_name) > 255)) {
            throw new \InvalidArgumentException('invalid length for $profile_name when calling CreateAccountWithProfileInput., must be smaller than or equal to 255.');
        }
        if ((mb_strlen($profile_name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $profile_name when calling CreateAccountWithProfileInput., must be bigger than or equal to 1.');
        }

        $this->container['profile_name'] = $profile_name;

        return $this;
    }

    /**
     * Gets profile_description
     *
     * @return string|null
     */
    public function getProfileDescription()
    {
        return $this->container['profile_description'];
    }

    /**
     * Sets profile_description
     *
     * @param string|null $profile_description Description of the profile node
     *
     * @return self
     */
    public function setProfileDescription($profile_description)
    {
        if (is_null($profile_description)) {
            throw new \InvalidArgumentException('non-nullable profile_description cannot be null');
        }
        if ((mb_strlen($profile_description) > 1000)) {
            throw new \InvalidArgumentException('invalid length for $profile_description when calling CreateAccountWithProfileInput., must be smaller than or equal to 1000.');
        }

        $this->container['profile_description'] = $profile_description;

        return $this;
    }

    /**
     * Gets profile_metadata
     *
     * @return object|null
     */
    public function getProfileMetadata()
    {
        return $this->container['profile_metadata'];
    }

    /**
     * Sets profile_metadata
     *
     * @param object|null $profile_metadata Metadata of the profile
     *
     * @return self
     */
    public function setProfileMetadata($profile_metadata)
    {
        if (is_null($profile_metadata)) {
            throw new \InvalidArgumentException('non-nullable profile_metadata cannot be null');
        }
        $this->container['profile_metadata'] = $profile_metadata;

        return $this;
    }

    /**
     * Gets edek_info
     *
     * @return \AffinidiTdk\Clients\VaultDataManagerClient\Model\EdekInfo
     */
    public function getEdekInfo()
    {
        return $this->container['edek_info'];
    }

    /**
     * Sets edek_info
     *
     * @param \AffinidiTdk\Clients\VaultDataManagerClient\Model\EdekInfo $edek_info edek_info
     *
     * @return self
     */
    public function setEdekInfo($edek_info)
    {
        if (is_null($edek_info)) {
            throw new \InvalidArgumentException('non-nullable edek_info cannot be null');
        }
        $this->container['edek_info'] = $edek_info;

        return $this;
    }

    /**
     * Gets dek
     *
     * @return string
     */
    public function getDek()
    {
        return $this->container['dek'];
    }

    /**
     * Sets dek
     *
     * @param string $dek A base64 encoded data encryption key, encrypted using VFS public key
     *
     * @return self
     */
    public function setDek($dek)
    {
        if (is_null($dek)) {
            throw new \InvalidArgumentException('non-nullable dek cannot be null');
        }
        $this->container['dek'] = $dek;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


