<?php
/**
 * NodeStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  AffinidiTdk\Clients\VaultDataManagerClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VaultFileSystem
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AffinidiTdk\Clients\VaultDataManagerClient\Model;
use \AffinidiTdk\Clients\VaultDataManagerClient\ObjectSerializer;

/**
 * NodeStatus Class Doc Comment
 *
 * @category Class
 * @description status of current node. INITIALIZED status is used for PROFILE/FILE node that was just created, before file was uploaded in s3 CREATED status is used, when the file for node is uploaded in s3. HIDDEN and DELETED statuses are used for deletion of Nodes
 * @package  AffinidiTdk\Clients\VaultDataManagerClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NodeStatus
{
    /**
     * Possible values of this enum
     */
    public const NOT_SET = 'NOT_SET';

    public const HIDDEN = 'HIDDEN';

    public const DELETED = 'DELETED';

    public const INITIALIZED = 'INITIALIZED';

    public const CREATED = 'CREATED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NOT_SET,
            self::HIDDEN,
            self::DELETED,
            self::INITIALIZED,
            self::CREATED
        ];
    }
}


