<?php
/**
 * NodeType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AffinidiTdk\Clients\VaultDataManagerClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VaultFileSystem
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AffinidiTdk\Clients\VaultDataManagerClient\Model;
use \AffinidiTdk\Clients\VaultDataManagerClient\ObjectSerializer;

/**
 * NodeType Class Doc Comment
 *
 * @category Class
 * @description type of the Node
 * @package  AffinidiTdk\Clients\VaultDataManagerClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NodeType
{
    /**
     * Possible values of this enum
     */
    public const VC_ROOT = 'VC_ROOT';

    public const VC = 'VC';

    public const FILE = 'FILE';

    public const FOLDER = 'FOLDER';

    public const PROFILE = 'PROFILE';

    public const ROOT_ELEMENT = 'ROOT_ELEMENT';

    public const TRASH_BIN = 'TRASH_BIN';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::VC_ROOT,
            self::VC,
            self::FILE,
            self::FOLDER,
            self::PROFILE,
            self::ROOT_ELEMENT,
            self::TRASH_BIN
        ];
    }
}


