<?php
/**
 * PatchAccountInput
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AffinidiTdk\Clients\VaultDataManagerClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VaultFileSystem
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AffinidiTdk\Clients\VaultDataManagerClient\Model;

use \ArrayAccess;
use \AffinidiTdk\Clients\VaultDataManagerClient\ObjectSerializer;

/**
 * PatchAccountInput Class Doc Comment
 *
 * @category Class
 * @package  AffinidiTdk\Clients\VaultDataManagerClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PatchAccountInput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PatchAccountInput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'did_proof' => 'string',
        'encrypted_dekek' => 'string',
        'owner_profile_id' => 'string',
        'owner_profile_did' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'did_proof' => null,
        'encrypted_dekek' => null,
        'owner_profile_id' => null,
        'owner_profile_did' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'did_proof' => false,
        'encrypted_dekek' => false,
        'owner_profile_id' => false,
        'owner_profile_did' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'did_proof' => 'didProof',
        'encrypted_dekek' => 'encryptedDekek',
        'owner_profile_id' => 'ownerProfileId',
        'owner_profile_did' => 'ownerProfileDid'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'did_proof' => 'setDidProof',
        'encrypted_dekek' => 'setEncryptedDekek',
        'owner_profile_id' => 'setOwnerProfileId',
        'owner_profile_did' => 'setOwnerProfileDid'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'did_proof' => 'getDidProof',
        'encrypted_dekek' => 'getEncryptedDekek',
        'owner_profile_id' => 'getOwnerProfileId',
        'owner_profile_did' => 'getOwnerProfileDid'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('did_proof', $data ?? [], null);
        $this->setIfExists('encrypted_dekek', $data ?? [], null);
        $this->setIfExists('owner_profile_id', $data ?? [], null);
        $this->setIfExists('owner_profile_did', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['did_proof'] === null) {
            $invalidProperties[] = "'did_proof' can't be null";
        }
        if ($this->container['encrypted_dekek'] === null) {
            $invalidProperties[] = "'encrypted_dekek' can't be null";
        }
        if ($this->container['owner_profile_id'] === null) {
            $invalidProperties[] = "'owner_profile_id' can't be null";
        }
        if ($this->container['owner_profile_did'] === null) {
            $invalidProperties[] = "'owner_profile_did' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets did_proof
     *
     * @return string
     */
    public function getDidProof()
    {
        return $this->container['did_proof'];
    }

    /**
     * Sets did_proof
     *
     * @param string $did_proof JWT that proves ownership of profile DID by requester
     *
     * @return self
     */
    public function setDidProof($did_proof)
    {
        if (is_null($did_proof)) {
            throw new \InvalidArgumentException('non-nullable did_proof cannot be null');
        }
        $this->container['did_proof'] = $did_proof;

        return $this;
    }

    /**
     * Gets encrypted_dekek
     *
     * @return string
     */
    public function getEncryptedDekek()
    {
        return $this->container['encrypted_dekek'];
    }

    /**
     * Sets encrypted_dekek
     *
     * @param string $encrypted_dekek A base64 encoded data encryption key, encrypted using VFS public key, required for PATCH operation on account
     *
     * @return self
     */
    public function setEncryptedDekek($encrypted_dekek)
    {
        if (is_null($encrypted_dekek)) {
            throw new \InvalidArgumentException('non-nullable encrypted_dekek cannot be null');
        }
        $this->container['encrypted_dekek'] = $encrypted_dekek;

        return $this;
    }

    /**
     * Gets owner_profile_id
     *
     * @return string
     */
    public function getOwnerProfileId()
    {
        return $this->container['owner_profile_id'];
    }

    /**
     * Sets owner_profile_id
     *
     * @param string $owner_profile_id A unique identifier of profile, required for PATCH operation on account
     *
     * @return self
     */
    public function setOwnerProfileId($owner_profile_id)
    {
        if (is_null($owner_profile_id)) {
            throw new \InvalidArgumentException('non-nullable owner_profile_id cannot be null');
        }
        $this->container['owner_profile_id'] = $owner_profile_id;

        return $this;
    }

    /**
     * Gets owner_profile_did
     *
     * @return string
     */
    public function getOwnerProfileDid()
    {
        return $this->container['owner_profile_did'];
    }

    /**
     * Sets owner_profile_did
     *
     * @param string $owner_profile_did DID that is associated with the profile, required for PATCH operation on account
     *
     * @return self
     */
    public function setOwnerProfileDid($owner_profile_did)
    {
        if (is_null($owner_profile_did)) {
            throw new \InvalidArgumentException('non-nullable owner_profile_did cannot be null');
        }
        $this->container['owner_profile_did'] = $owner_profile_did;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


