<?php
/**
 * SignCredentialsDm1JwtResultDtoTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AffinidiTdk\Clients\WalletsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CloudWalletEssentials
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AffinidiTdk\Clients\WalletsClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SignCredentialsDm1JwtResultDtoTest Class Doc Comment
 *
 * @category    Class
 * @description DTO contains signed credential
 * @package     AffinidiTdk\Clients\WalletsClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SignCredentialsDm1JwtResultDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SignCredentialsDm1JwtResultDto"
     */
    public function testSignCredentialsDm1JwtResultDto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "credential"
     */
    public function testPropertyCredential()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
