<?php
/**
 * InvalidParameterError
 * PHP version 7.4
 *
 * @category Class
 * @package  AffinidiTdk\Clients\WalletsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CloudWalletEssentials
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AffinidiTdk\Clients\WalletsClient;

use \Exception;

/**
 * InvalidParameterError
 *
 * @category Class
 * @package  AffinidiTdk\Clients\WalletsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InvalidParameterError extends Exception
{
    /**
     * @var string
     */
    private $name = 'InvalidParameterError';

    /**
     * @var array
     */
    private $details;

    /**
     * @var string
     */
    private $traceId;

    /**
     * @param string $issue
     * @param string $traceId
     */
    public function __construct(string $message, array $details, string $traceId)
    {
        $message = [
            'name' => $this->name,
            'message' => $message,
            'details' => $details,
            'traceId' => $traceId
        ];

        parent::__construct(json_encode($message), 400);
        $this->details = $details;
        $this->traceId = $traceId;
    }
}
