<?php
/**
 * BatchCredentialResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  AffinidiTdk\Clients\CredentialIssuanceClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CredentialIssuanceService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AffinidiTdk\Clients\CredentialIssuanceClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * BatchCredentialResponseTest Class Doc Comment
 *
 * @category    Class
 * @description BatchCredentialResponse
 * @package     AffinidiTdk\Clients\CredentialIssuanceClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BatchCredentialResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "BatchCredentialResponse"
     */
    public function testBatchCredentialResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "credential_responses"
     */
    public function testPropertyCredentialResponses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "c_nonce"
     */
    public function testPropertyCNonce()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "c_nonce_expires_in"
     */
    public function testPropertyCNonceExpiresIn()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
