<?php
/**
 * RightsEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AffinidiTdk\Clients\IamClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Iam
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AffinidiTdk\Clients\IamClient\Model;
use \AffinidiTdk\Clients\IamClient\ObjectSerializer;

/**
 * RightsEnum Class Doc Comment
 *
 * @category Class
 * @package  AffinidiTdk\Clients\IamClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RightsEnum
{
    /**
     * Possible values of this enum
     */
    public const VFS_READ = 'vfs-read';

    public const VFS_WRITE = 'vfs-write';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::VFS_READ,
            self::VFS_WRITE
        ];
    }
}


