name: branch

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  actions: read
  contents: read

jobs:
  security:
    permissions:
      contents: read
      checks: read
      statuses: read
      security-events: write
    uses: affinidi/pipeline-security/.github/workflows/security-scanners.yml@main
    with:
      config-path: .github/labeler.yml
    secrets: inherit  
  validate-package:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install

    - name: Lint PHP files
      uses: overtrue/phplint@main
      with:
        path: .
        options: --exclude=vendor

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-