name: branch

on:
  pull_request_target:
    types:
      - opened
      - synchronize

permissions:
  actions: read
  contents: read

jobs:
  security:
    permissions:
      contents: read
      checks: read
      statuses: read
      security-events: write
    uses: affinidi/pipeline-security/.github/workflows/security-scanners.yml@main
    with:
      config-path: .github/labeler.yml
    secrets: inherit  
  validate-package:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
        
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Validate dependencies
      uses: php-actions/composer@master
      with:
          command: validate
    - name: Install dependencies
      uses: php-actions/composer@v6

    - name: Lint PHP files
      uses: overtrue/phplint@main
      with:
        path: .
        options: --exclude=vendor

    - name: create empty .env file.
      run: echo "" > tests/Helpers/.env

    - uses: php-actions/phpstan@v3
      with:
        path: src/AuthProvider src/Common
        level: 5
        memory_limit: 2048m
